schema_version = "1.0.0"

id = "material_utilities_Unofficial"
version = "3.0.2"
name = "Material Utilities Unofficial"
tagline = "Extended material management tools (Community Fork) - DO NOT USE WITH ORIGINAL ADD-ON"
maintainer = "Community Fork"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
# permissions = []

# Optional link to documentation, support, source files, etc
website = "https://github.com/ChrisHinde/MaterialUtilities"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Github"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2024 ChrisHinde"
]